default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { '35432' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>
  database: <%= ENV.fetch("DATABASE_NAME") { 'sellmybike_development' } %>

development:
  <<: *default

test:
  <<: *default
  database: sellmybike_test

production:
  <<: *default
  database: sellmybike_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
